// clientes/livros-next/pages/LivroLista.tsx
import { useEffect, useState } from 'react';
import Head from 'next/head';
import { Menu } from '@/componentes/Menu';

// import styles from '../styles/Home.module.css';
import ControleEditora from '@/classes/controle/ControleEditora';
import ControleLivro from '@/classes/controle/ControleLivros';
// import Livro from '@/classes/modelo/Livro';

const controleEditora = new ControleEditora();
const controleLivros = new ControleLivro();
// const baseURL = 'http://localhost:3000/api/livros';

const LivroLista: React.FC = () => {
  const [livros, setLivros] = useState<Livro[]>([]);
  const [carregado, setCarregado] = useState(false);

  useEffect(() => {
    controleLivros.obterLivros()
      .then( livros => {

        setLivros( livros );
        setCarregado(true);
      })
      .catch((error) => {
        console.error('Erro ao obter os livros:', error);
      });
  },[carregado]);

 // const obterLivros = async () => await fetch(baseURL).then( resp => resp.json() );
 

  // const excluirLivro = async (codigo: number) => {
  //   const response = await fetch(`${baseURL}/${codigo}`, {
  //     method: 'DELETE',
  //   });
  //   return response.ok;
  // };

  const excluir = async (codigo: string) => {
      console.log( "codigo", codigo)
      controleLivros.excluir(codigo).then(() => {
      const livrosAtualizados = livros.filter((livro) => livro._id !== codigo);
      setLivros(livrosAtualizados);
      setCarregado(false);
    })
  };

  return (
    <div >
      <Head>
        <title>LivroLista</title>
      </Head>
      <Menu />
      <main className="container text-start">
        <h1><b>Catálogo de Livros</b></h1>
        <table className='table table-striped mt-3'>
          <thead>
            <tr className="table-dark">
              <th className="col-4">Título</th>
              <th className="col-2">Editora</th>
              <th className="col-2">Autor</th>
              <th className="col-2">Resumo</th>
            </tr>
          </thead>
          <tbody>
            {carregado &&
              livros.map((livro, index) => (
                <LinhaLivro
                  key={index}
                  livro={livro}
                  excluir={excluir}
                />
              ))}
          </tbody>
        </table>
      </main>
    </div>
  );
};

interface Livro {
  _id: string|null;
  titulo: string;
  autores: string[];
  resumo: string;
  codEditora:number;
}

interface LinhaLivroProps {
  livro: Livro;
  excluir: (codigo: string) => void;
}

const LinhaLivro: React.FC<LinhaLivroProps> = ({ livro, excluir }) => {
  return (
    <tr>

      <td>
        {livro.titulo} <br />
       <button className="btn btn-danger" onClick={() => excluir(livro._id)}>Excluir</button>
      </td>
      <td>
          { controleEditora.getNomeEditora( livro.codEditora ) }
      </td>
      <td>
        <ul>
          {livro.autores.map((autor, index) => ( <li key={index}>{autor}</li>  ))}
        </ul>
      </td>
      <td>{livro.resumo}</td>

    </tr>
  );
};

export default LivroLista;

// clientes/livros-angular/src/app/livro-lista/livro-lista.component.ts
import { Component, OnInit } from '@angular/core';
import  Editora  from '../editora';
import  Livro  from '../livro';
import  ControleEditoraService from '../controle-editora.service';
import  ControleLivrosService  from '../controle-livros.service';

@Component({
  selector: 'app-livro-lista',
  templateUrl: './livro-lista.component.html',
  styleUrls: ['./livro-lista.component.css']
})
export class LivroListaComponent implements OnInit {
  editoras: Editora[] = [];
  livros: Livro[] = [];
  constructor(private servEditora: ControleEditoraService, private servLivros: ControleLivrosService) { }

  async ngOnInit() {
    this.editoras = this.servEditora.getEditoras();
    this.livros = await this.servLivros.obterLivros().then( livros => livros );
  }
  
  excluir= async (codigo: string) => {
    await this.servLivros.excluir(codigo);
    this.livros = await this.servLivros.obterLivros().then( livros => livros );
  }

  obterNome = (codEditora: number): string => this.servEditora.getNomeEditora(codEditora);
  
}

<main class="container text-start">
    <h1><b>Catálogo de Livros</b></h1>
    <table class="table table-striped">
      <thead>
        <tr class="table-dark">
            <th class="col-2">Título</th>
            <th class="col-4">Resumo</th>
            <th class="col-2">Editora</th>
            <th class="col-2">Autores</th>
        </tr>
      </thead>
      <tbody>
        <tr *ngFor="let livro of livros">
          <td>
            {{ livro.titulo }}<br>
            <button class="btn btn-danger" (click)="excluir(livro._id!)">Excluir</button>
          </td>
          <td>{{ livro.resumo }}</td>
          <td>{{ obterNome(livro.codEditora) }}</td>
          <td>
            <ul>
              <li *ngFor="let autor of livro.autores">{{ autor }}</li>
            </ul>
          </td>
  
        </tr>
      </tbody>
    </table>
  </main>
